//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.28 at 10:22:16 AM EDT 
//


package com.sciquest.po;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "formType",
    "formTitle",
    "catalogNumber",
    "description",
    "formProductSize",
    "quantity",
    "formProductUnitOfMeasure",
    "unspsc",
    "productClassification",
    "manufacturerInfo",
    "commodityCode",
    "contractNumber",
    "capitalExpense",
    "taxable",
    "formFields"
})
@XmlRootElement(name = "Form")
public class Form {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String configId;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String configVersion;
    @XmlElement(name = "FormType", required = true)
    protected String formType;
    @XmlElement(name = "FormTitle", required = true)
    protected String formTitle;
    @XmlElement(name = "CatalogNumber")
    protected String catalogNumber;
    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "FormProductSize")
    protected List<FormProductSize> formProductSize;
    @XmlElement(name = "Quantity")
    protected String quantity;
    @XmlElement(name = "FormProductUnitOfMeasure")
    protected List<FormProductUnitOfMeasure> formProductUnitOfMeasure;
    @XmlElement(name = "UNSPSC")
    protected String unspsc;
    @XmlElement(name = "ProductClassification")
    protected List<ProductClassification> productClassification;
    @XmlElement(name = "ManufacturerInfo")
    protected ManufacturerInfo manufacturerInfo;
    @XmlElement(name = "CommodityCode")
    protected String commodityCode;
    @XmlElement(name = "ContractNumber")
    protected String contractNumber;
    @XmlElement(name = "CapitalExpense")
    protected String capitalExpense;
    @XmlElement(name = "Taxable")
    protected String taxable;
    @XmlElement(name = "FormFields", required = true)
    protected FormFields formFields;

    /**
     * Gets the value of the configId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigId() {
        return configId;
    }

    /**
     * Sets the value of the configId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigId(String value) {
        this.configId = value;
    }

    /**
     * Gets the value of the configVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConfigVersion() {
        return configVersion;
    }

    /**
     * Sets the value of the configVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConfigVersion(String value) {
        this.configVersion = value;
    }

    /**
     * Gets the value of the formType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormType() {
        return formType;
    }

    /**
     * Sets the value of the formType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormType(String value) {
        this.formType = value;
    }

    /**
     * Gets the value of the formTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormTitle() {
        return formTitle;
    }

    /**
     * Sets the value of the formTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormTitle(String value) {
        this.formTitle = value;
    }

    /**
     * Gets the value of the catalogNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatalogNumber() {
        return catalogNumber;
    }

    /**
     * Sets the value of the catalogNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatalogNumber(String value) {
        this.catalogNumber = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the formProductSize property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formProductSize property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormProductSize().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormProductSize }
     * 
     * 
     */
    public List<FormProductSize> getFormProductSize() {
        if (formProductSize == null) {
            formProductSize = new ArrayList<FormProductSize>();
        }
        return this.formProductSize;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantity(String value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the formProductUnitOfMeasure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formProductUnitOfMeasure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormProductUnitOfMeasure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormProductUnitOfMeasure }
     * 
     * 
     */
    public List<FormProductUnitOfMeasure> getFormProductUnitOfMeasure() {
        if (formProductUnitOfMeasure == null) {
            formProductUnitOfMeasure = new ArrayList<FormProductUnitOfMeasure>();
        }
        return this.formProductUnitOfMeasure;
    }

    /**
     * Gets the value of the unspsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNSPSC() {
        return unspsc;
    }

    /**
     * Sets the value of the unspsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNSPSC(String value) {
        this.unspsc = value;
    }

    /**
     * Gets the value of the productClassification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productClassification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductClassification }
     * 
     * 
     */
    public List<ProductClassification> getProductClassification() {
        if (productClassification == null) {
            productClassification = new ArrayList<ProductClassification>();
        }
        return this.productClassification;
    }

    /**
     * Gets the value of the manufacturerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ManufacturerInfo }
     *     
     */
    public ManufacturerInfo getManufacturerInfo() {
        return manufacturerInfo;
    }

    /**
     * Sets the value of the manufacturerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ManufacturerInfo }
     *     
     */
    public void setManufacturerInfo(ManufacturerInfo value) {
        this.manufacturerInfo = value;
    }

    /**
     * Gets the value of the commodityCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommodityCode() {
        return commodityCode;
    }

    /**
     * Sets the value of the commodityCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommodityCode(String value) {
        this.commodityCode = value;
    }

    /**
     * Gets the value of the contractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * Sets the value of the contractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNumber(String value) {
        this.contractNumber = value;
    }

    /**
     * Gets the value of the capitalExpense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapitalExpense() {
        return capitalExpense;
    }

    /**
     * Sets the value of the capitalExpense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapitalExpense(String value) {
        this.capitalExpense = value;
    }

    /**
     * Gets the value of the taxable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxable() {
        return taxable;
    }

    /**
     * Sets the value of the taxable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxable(String value) {
        this.taxable = value;
    }

    /**
     * Gets the value of the formFields property.
     * 
     * @return
     *     possible object is
     *     {@link FormFields }
     *     
     */
    public FormFields getFormFields() {
        return formFields;
    }

    /**
     * Sets the value of the formFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormFields }
     *     
     */
    public void setFormFields(FormFields value) {
        this.formFields = value;
    }

}
