//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.28 at 10:22:16 AM EDT 
//


package com.sciquest.po;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "unitPrice",
    "extendedPrice",
    "shippingCharges",
    "handlingCharges",
    "tax1",
    "tax2"
})
@XmlRootElement(name = "LineCharges")
public class LineCharges {

    @XmlElement(name = "UnitPrice", required = true)
    protected UnitPrice unitPrice;
    @XmlElement(name = "ExtendedPrice")
    protected ExtendedPrice extendedPrice;
    @XmlElement(name = "ShippingCharges")
    protected ShippingCharges shippingCharges;
    @XmlElement(name = "HandlingCharges")
    protected HandlingCharges handlingCharges;
    @XmlElement(name = "Tax1")
    protected Tax1 tax1;
    @XmlElement(name = "Tax2")
    protected Tax2 tax2;

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link UnitPrice }
     *     
     */
    public UnitPrice getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitPrice }
     *     
     */
    public void setUnitPrice(UnitPrice value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the extendedPrice property.
     * 
     * @return
     *     possible object is
     *     {@link ExtendedPrice }
     *     
     */
    public ExtendedPrice getExtendedPrice() {
        return extendedPrice;
    }

    /**
     * Sets the value of the extendedPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtendedPrice }
     *     
     */
    public void setExtendedPrice(ExtendedPrice value) {
        this.extendedPrice = value;
    }

    /**
     * Gets the value of the shippingCharges property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingCharges }
     *     
     */
    public ShippingCharges getShippingCharges() {
        return shippingCharges;
    }

    /**
     * Sets the value of the shippingCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingCharges }
     *     
     */
    public void setShippingCharges(ShippingCharges value) {
        this.shippingCharges = value;
    }

    /**
     * Gets the value of the handlingCharges property.
     * 
     * @return
     *     possible object is
     *     {@link HandlingCharges }
     *     
     */
    public HandlingCharges getHandlingCharges() {
        return handlingCharges;
    }

    /**
     * Sets the value of the handlingCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlingCharges }
     *     
     */
    public void setHandlingCharges(HandlingCharges value) {
        this.handlingCharges = value;
    }

    /**
     * Gets the value of the tax1 property.
     * 
     * @return
     *     possible object is
     *     {@link Tax1 }
     *     
     */
    public Tax1 getTax1() {
        return tax1;
    }

    /**
     * Sets the value of the tax1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tax1 }
     *     
     */
    public void setTax1(Tax1 value) {
        this.tax1 = value;
    }

    /**
     * Gets the value of the tax2 property.
     * 
     * @return
     *     possible object is
     *     {@link Tax2 }
     *     
     */
    public Tax2 getTax2() {
        return tax2;
    }

    /**
     * Sets the value of the tax2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tax2 }
     *     
     */
    public void setTax2(Tax2 value) {
        this.tax2 = value;
    }

}
