//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.28 at 10:22:16 AM EDT 
//


package com.sciquest.po;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "purchaseOrderRef",
    "purchaseOrderLineRef"
})
@XmlRootElement(name = "ObjectErrors")
public class ObjectErrors {

    @XmlElement(name = "PurchaseOrderRef")
    protected List<PurchaseOrderRef> purchaseOrderRef;
    @XmlElement(name = "PurchaseOrderLineRef")
    protected List<PurchaseOrderLineRef> purchaseOrderLineRef;

    /**
     * Gets the value of the purchaseOrderRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the purchaseOrderRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPurchaseOrderRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PurchaseOrderRef }
     * 
     * 
     */
    public List<PurchaseOrderRef> getPurchaseOrderRef() {
        if (purchaseOrderRef == null) {
            purchaseOrderRef = new ArrayList<PurchaseOrderRef>();
        }
        return this.purchaseOrderRef;
    }

    /**
     * Gets the value of the purchaseOrderLineRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the purchaseOrderLineRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPurchaseOrderLineRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PurchaseOrderLineRef }
     * 
     * 
     */
    public List<PurchaseOrderLineRef> getPurchaseOrderLineRef() {
        if (purchaseOrderLineRef == null) {
            purchaseOrderLineRef = new ArrayList<PurchaseOrderLineRef>();
        }
        return this.purchaseOrderLineRef;
    }

}
