//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.28 at 10:22:16 AM EDT 
//


package com.sciquest.po;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.rpi.cmms package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.rpi.cmms
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ManufacturerInfo }
     * 
     */
    public ManufacturerInfo createManufacturerInfo() {
        return new ManufacturerInfo();
    }

    /**
     * Create an instance of {@link ExternalInfo }
     * 
     */
    public ExternalInfo createExternalInfo() {
        return new ExternalInfo();
    }

    /**
     * Create an instance of {@link Money }
     * 
     */
    public Money createMoney() {
        return new Money();
    }

    /**
     * Create an instance of {@link TaxShippingHandling }
     * 
     */
    public TaxShippingHandling createTaxShippingHandling() {
        return new TaxShippingHandling();
    }

    /**
     * Create an instance of {@link Fax }
     * 
     */
    public Fax createFax() {
        return new Fax();
    }

    /**
     * Create an instance of {@link InternalItemInfo }
     * 
     */
    public InternalItemInfo createInternalItemInfo() {
        return new InternalItemInfo();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link Discount }
     * 
     */
    public Discount createDiscount() {
        return new Discount();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link UserProfile }
     * 
     */
    public UserProfile createUserProfile() {
        return new UserProfile();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link CustomFieldValue }
     * 
     */
    public CustomFieldValue createCustomFieldValue() {
        return new CustomFieldValue();
    }

    /**
     * Create an instance of {@link ShippingCharges }
     * 
     */
    public ShippingCharges createShippingCharges() {
        return new ShippingCharges();
    }

    /**
     * Create an instance of {@link Error }
     * 
     */
    public Error createError() {
        return new Error();
    }

    /**
     * Create an instance of {@link RequisitionRef }
     * 
     */
    public RequisitionRef createRequisitionRef() {
        return new RequisitionRef();
    }

    /**
     * Create an instance of {@link ExchangeRates }
     * 
     */
    public ExchangeRates createExchangeRates() {
        return new ExchangeRates();
    }

    /**
     * Create an instance of {@link TSHConfig }
     * 
     */
    public TSHConfig createTSHConfig() {
        return new TSHConfig();
    }

    /**
     * Create an instance of {@link Action }
     * 
     */
    public Action createAction() {
        return new Action();
    }

    /**
     * Create an instance of {@link FormField }
     * 
     */
    public FormField createFormField() {
        return new FormField();
    }

    /**
     * Create an instance of {@link FreeThresholdLimit }
     * 
     */
    public FreeThresholdLimit createFreeThresholdLimit() {
        return new FreeThresholdLimit();
    }

    /**
     * Create an instance of {@link InternalInfo }
     * 
     */
    public InternalInfo createInternalInfo() {
        return new InternalInfo();
    }

    /**
     * Create an instance of {@link ShipTo }
     * 
     */
    public ShipTo createShipTo() {
        return new ShipTo();
    }

    /**
     * Create an instance of {@link ShippingMethod }
     * 
     */
    public ShippingMethod createShippingMethod() {
        return new ShippingMethod();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link CreditCard }
     * 
     */
    public CreditCard createCreditCard() {
        return new CreditCard();
    }

    /**
     * Create an instance of {@link Supplier }
     * 
     */
    public Supplier createSupplier() {
        return new Supplier();
    }

    /**
     * Create an instance of {@link Terms }
     * 
     */
    public Terms createTerms() {
        return new Terms();
    }

    /**
     * Create an instance of {@link ExtendedItemInfo }
     * 
     */
    public ExtendedItemInfo createExtendedItemInfo() {
        return new ExtendedItemInfo();
    }

    /**
     * Create an instance of {@link PaymentInfo }
     * 
     */
    public PaymentInfo createPaymentInfo() {
        return new PaymentInfo();
    }

    /**
     * Create an instance of {@link ExtendedPrice }
     * 
     */
    public ExtendedPrice createExtendedPrice() {
        return new ExtendedPrice();
    }

    /**
     * Create an instance of {@link AddressLine }
     * 
     */
    public AddressLine createAddressLine() {
        return new AddressLine();
    }

    /**
     * Create an instance of {@link Tax1 }
     * 
     */
    public Tax1 createTax1() {
        return new Tax1();
    }

    /**
     * Create an instance of {@link WorkflowStatus }
     * 
     */
    public WorkflowStatus createWorkflowStatus() {
        return new WorkflowStatus();
    }

    /**
     * Create an instance of {@link DistributionMethod }
     * 
     */
    public DistributionMethod createDistributionMethod() {
        return new DistributionMethod();
    }

    /**
     * Create an instance of {@link Authentication }
     * 
     */
    public Authentication createAuthentication() {
        return new Authentication();
    }

    /**
     * Create an instance of {@link Attachments }
     * 
     */
    public Attachments createAttachments() {
        return new Attachments();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link APStatus }
     * 
     */
    public APStatus createAPStatus() {
        return new APStatus();
    }

    /**
     * Create an instance of {@link Measurement }
     * 
     */
    public Measurement createMeasurement() {
        return new Measurement();
    }

    /**
     * Create an instance of {@link Requestor }
     * 
     */
    public Requestor createRequestor() {
        return new Requestor();
    }

    /**
     * Create an instance of {@link UnitPrice }
     * 
     */
    public UnitPrice createUnitPrice() {
        return new UnitPrice();
    }

    /**
     * Create an instance of {@link ProductSize }
     * 
     */
    public ProductSize createProductSize() {
        return new ProductSize();
    }

    /**
     * Create an instance of {@link POLine }
     * 
     */
    public POLine createPOLine() {
        return new POLine();
    }

    /**
     * Create an instance of {@link Carrier }
     * 
     */
    public Carrier createCarrier() {
        return new Carrier();
    }

    /**
     * Create an instance of {@link ObjectErrors }
     * 
     */
    public ObjectErrors createObjectErrors() {
        return new ObjectErrors();
    }

    /**
     * Create an instance of {@link TelephoneNumber }
     * 
     */
    public TelephoneNumber createTelephoneNumber() {
        return new TelephoneNumber();
    }

    /**
     * Create an instance of {@link CustomFieldValueSet }
     * 
     */
    public CustomFieldValueSet createCustomFieldValueSet() {
        return new CustomFieldValueSet();
    }

    /**
     * Create an instance of {@link DeliveryInfo }
     * 
     */
    public DeliveryInfo createDeliveryInfo() {
        return new DeliveryInfo();
    }

    /**
     * Create an instance of {@link FormFields }
     * 
     */
    public FormFields createFormFields() {
        return new FormFields();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link PurchaseOrderRef }
     * 
     */
    public PurchaseOrderRef createPurchaseOrderRef() {
        return new PurchaseOrderRef();
    }

    /**
     * Create an instance of {@link ExternalItemInfo }
     * 
     */
    public ExternalItemInfo createExternalItemInfo() {
        return new ExternalItemInfo();
    }

    /**
     * Create an instance of {@link Tax2 }
     * 
     */
    public Tax2 createTax2() {
        return new Tax2();
    }

    /**
     * Create an instance of {@link PurchaseOrderMessage }
     * 
     */
    public PurchaseOrderMessage createPurchaseOrderMessage() {
        return new PurchaseOrderMessage();
    }

    /**
     * Create an instance of {@link PurchaseOrder }
     * 
     */
    public PurchaseOrder createPurchaseOrder() {
        return new PurchaseOrder();
    }

    /**
     * Create an instance of {@link Form }
     * 
     */
    public Form createForm() {
        return new Form();
    }

    /**
     * Create an instance of {@link ExtendedPurchaseOrder }
     * 
     */
    public ExtendedPurchaseOrder createExtendedPurchaseOrder() {
        return new ExtendedPurchaseOrder();
    }

    /**
     * Create an instance of {@link ContactAddress }
     * 
     */
    public ContactAddress createContactAddress() {
        return new ContactAddress();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link Attachment }
     * 
     */
    public Attachment createAttachment() {
        return new Attachment();
    }

    /**
     * Create an instance of {@link ResponseMessage }
     * 
     */
    public ResponseMessage createResponseMessage() {
        return new ResponseMessage();
    }

    /**
     * Create an instance of {@link FormFieldValue }
     * 
     */
    public FormFieldValue createFormFieldValue() {
        return new FormFieldValue();
    }

    /**
     * Create an instance of {@link TSHActualCharge }
     * 
     */
    public TSHActualCharge createTSHActualCharge() {
        return new TSHActualCharge();
    }

    /**
     * Create an instance of {@link SupplierInfo }
     * 
     */
    public SupplierInfo createSupplierInfo() {
        return new SupplierInfo();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link LineCharges }
     * 
     */
    public LineCharges createLineCharges() {
        return new LineCharges();
    }

    /**
     * Create an instance of {@link FormProductSize }
     * 
     */
    public FormProductSize createFormProductSize() {
        return new FormProductSize();
    }

    /**
     * Create an instance of {@link RequisitionLineRef }
     * 
     */
    public RequisitionLineRef createRequisitionLineRef() {
        return new RequisitionLineRef();
    }

    /**
     * Create an instance of {@link FlatChargeByOrder }
     * 
     */
    public FlatChargeByOrder createFlatChargeByOrder() {
        return new FlatChargeByOrder();
    }

    /**
     * Create an instance of {@link ExchangeRate }
     * 
     */
    public ExchangeRate createExchangeRate() {
        return new ExchangeRate();
    }

    /**
     * Create an instance of {@link ProductClassification }
     * 
     */
    public ProductClassification createProductClassification() {
        return new ProductClassification();
    }

    /**
     * Create an instance of {@link PurchaseOrderLineRef }
     * 
     */
    public PurchaseOrderLineRef createPurchaseOrderLineRef() {
        return new PurchaseOrderLineRef();
    }

    /**
     * Create an instance of {@link FormProductUnitOfMeasure }
     * 
     */
    public FormProductUnitOfMeasure createFormProductUnitOfMeasure() {
        return new FormProductUnitOfMeasure();
    }

    /**
     * Create an instance of {@link POClause }
     * 
     */
    public POClause createPOClause() {
        return new POClause();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link BillTo }
     * 
     */
    public BillTo createBillTo() {
        return new BillTo();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link XopInclude }
     * 
     */
    public XopInclude createXopInclude() {
        return new XopInclude();
    }

    /**
     * Create an instance of {@link GeneralItemInfo }
     * 
     */
    public GeneralItemInfo createGeneralItemInfo() {
        return new GeneralItemInfo();
    }

    /**
     * Create an instance of {@link Expedite }
     * 
     */
    public Expedite createExpedite() {
        return new Expedite();
    }

    /**
     * Create an instance of {@link BuyerInfo }
     * 
     */
    public BuyerInfo createBuyerInfo() {
        return new BuyerInfo();
    }

    /**
     * Create an instance of {@link HandlingCharges }
     * 
     */
    public HandlingCharges createHandlingCharges() {
        return new HandlingCharges();
    }

    /**
     * Create an instance of {@link FlatChargeByLine }
     * 
     */
    public FlatChargeByLine createFlatChargeByLine() {
        return new FlatChargeByLine();
    }

    /**
     * Create an instance of {@link HandlingCost }
     * 
     */
    public HandlingCost createHandlingCost() {
        return new HandlingCost();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link POHeader }
     * 
     */
    public POHeader createPOHeader() {
        return new POHeader();
    }

    /**
     * Create an instance of {@link ProductUnitOfMeasure }
     * 
     */
    public ProductUnitOfMeasure createProductUnitOfMeasure() {
        return new ProductUnitOfMeasure();
    }

    /**
     * Create an instance of {@link OrderDistribution }
     * 
     */
    public OrderDistribution createOrderDistribution() {
        return new OrderDistribution();
    }

    /**
     * Create an instance of {@link POClauses }
     * 
     */
    public POClauses createPOClauses() {
        return new POClauses();
    }

    /**
     * Create an instance of {@link SupplierStatus }
     * 
     */
    public SupplierStatus createSupplierStatus() {
        return new SupplierStatus();
    }

}
