//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.28 at 10:22:16 AM EDT 
//


package com.sciquest.po;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "distributionMethod",
    "distributionCompletionDate",
    "orderAcceptanceInstructions"
})
@XmlRootElement(name = "OrderDistribution")
public class OrderDistribution {

    @XmlElement(name = "DistributionMethod")
    protected List<DistributionMethod> distributionMethod;
    @XmlElement(name = "DistributionCompletionDate")
    protected String distributionCompletionDate;
    @XmlElement(name = "OrderAcceptanceInstructions")
    protected String orderAcceptanceInstructions;

    /**
     * Gets the value of the distributionMethod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the distributionMethod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDistributionMethod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DistributionMethod }
     * 
     * 
     */
    public List<DistributionMethod> getDistributionMethod() {
        if (distributionMethod == null) {
            distributionMethod = new ArrayList<DistributionMethod>();
        }
        return this.distributionMethod;
    }

    /**
     * Gets the value of the distributionCompletionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistributionCompletionDate() {
        return distributionCompletionDate;
    }

    /**
     * Sets the value of the distributionCompletionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistributionCompletionDate(String value) {
        this.distributionCompletionDate = value;
    }

    /**
     * Gets the value of the orderAcceptanceInstructions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderAcceptanceInstructions() {
        return orderAcceptanceInstructions;
    }

    /**
     * Sets the value of the orderAcceptanceInstructions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderAcceptanceInstructions(String value) {
        this.orderAcceptanceInstructions = value;
    }

}
