//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.28 at 10:22:16 AM EDT 
//


package com.sciquest.po;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clauseNumber",
    "clauseName",
    "clauseText"
})
@XmlRootElement(name = "POClause")
public class POClause {

    @XmlElement(name = "ClauseNumber", required = true)
    protected String clauseNumber;
    @XmlElement(name = "ClauseName", required = true)
    protected String clauseName;
    @XmlElement(name = "ClauseText", required = true)
    protected String clauseText;

    /**
     * Gets the value of the clauseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClauseNumber() {
        return clauseNumber;
    }

    /**
     * Sets the value of the clauseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClauseNumber(String value) {
        this.clauseNumber = value;
    }

    /**
     * Gets the value of the clauseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClauseName() {
        return clauseName;
    }

    /**
     * Sets the value of the clauseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClauseName(String value) {
        this.clauseName = value;
    }

    /**
     * Gets the value of the clauseText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClauseText() {
        return clauseText;
    }

    /**
     * Sets the value of the clauseText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClauseText(String value) {
        this.clauseText = value;
    }

}
