//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.28 at 10:22:16 AM EDT 
//


package com.sciquest.po;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "workflowStatus",
    "supplierStatus",
    "apStatus",
    "revisionNumber",
    "revisionDate",
    "distributeRevision",
    "poNumber",
    "alternatePONumber",
    "requestor",
    "buyerInfo",
    "department",
    "priority",
    "createDateTime",
    "initialRevisionDateTime",
    "accountingDate",
    "supplier",
    "orderDistribution",
    "billTo",
    "shipTo",
    "paymentInfo",
    "internalInfo",
    "externalInfo",
    "freightOnBoard",
    "customFieldValueSet",
    "requisitionRef",
    "shippingCharges",
    "handlingCharges",
    "tax1",
    "tax2",
    "poClauses",
    "exchangeRates"
})
@XmlRootElement(name = "POHeader")
public class POHeader {

    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String id;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlElement(name = "WorkflowStatus")
    protected WorkflowStatus workflowStatus;
    @XmlElement(name = "SupplierStatus")
    protected SupplierStatus supplierStatus;
    @XmlElement(name = "APStatus")
    protected APStatus apStatus;
    @XmlElement(name = "RevisionNumber")
    protected String revisionNumber;
    @XmlElement(name = "RevisionDate")
    protected String revisionDate;
    @XmlElement(name = "DistributeRevision")
    protected String distributeRevision;
    @XmlElement(name = "PONumber")
    protected String poNumber;
    @XmlElement(name = "AlternatePONumber")
    protected String alternatePONumber;
    @XmlElement(name = "Requestor")
    protected Requestor requestor;
    @XmlElement(name = "BuyerInfo")
    protected BuyerInfo buyerInfo;
    @XmlElement(name = "Department")
    protected String department;
    @XmlElement(name = "Priority")
    protected String priority;
    @XmlElement(name = "CreateDateTime")
    protected String createDateTime;
    @XmlElement(name = "InitialRevisionDateTime")
    protected String initialRevisionDateTime;
    @XmlElement(name = "AccountingDate")
    protected String accountingDate;
    @XmlElement(name = "Supplier", required = true)
    protected Supplier supplier;
    @XmlElement(name = "OrderDistribution")
    protected OrderDistribution orderDistribution;
    @XmlElement(name = "BillTo")
    protected BillTo billTo;
    @XmlElement(name = "ShipTo")
    protected ShipTo shipTo;
    @XmlElement(name = "PaymentInfo")
    protected PaymentInfo paymentInfo;
    @XmlElement(name = "InternalInfo")
    protected InternalInfo internalInfo;
    @XmlElement(name = "ExternalInfo")
    protected ExternalInfo externalInfo;
    @XmlElement(name = "FreightOnBoard")
    protected String freightOnBoard;
    @XmlElement(name = "CustomFieldValueSet")
    protected List<CustomFieldValueSet> customFieldValueSet;
    @XmlElement(name = "RequisitionRef")
    protected RequisitionRef requisitionRef;
    @XmlElement(name = "ShippingCharges")
    protected ShippingCharges shippingCharges;
    @XmlElement(name = "HandlingCharges")
    protected HandlingCharges handlingCharges;
    @XmlElement(name = "Tax1")
    protected Tax1 tax1;
    @XmlElement(name = "Tax2")
    protected Tax2 tax2;
    @XmlElement(name = "POClauses")
    protected POClauses poClauses;
    @XmlElement(name = "ExchangeRates")
    protected ExchangeRates exchangeRates;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the workflowStatus property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowStatus }
     *     
     */
    public WorkflowStatus getWorkflowStatus() {
        return workflowStatus;
    }

    /**
     * Sets the value of the workflowStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowStatus }
     *     
     */
    public void setWorkflowStatus(WorkflowStatus value) {
        this.workflowStatus = value;
    }

    /**
     * Gets the value of the supplierStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierStatus }
     *     
     */
    public SupplierStatus getSupplierStatus() {
        return supplierStatus;
    }

    /**
     * Sets the value of the supplierStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierStatus }
     *     
     */
    public void setSupplierStatus(SupplierStatus value) {
        this.supplierStatus = value;
    }

    /**
     * Gets the value of the apStatus property.
     * 
     * @return
     *     possible object is
     *     {@link APStatus }
     *     
     */
    public APStatus getAPStatus() {
        return apStatus;
    }

    /**
     * Sets the value of the apStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link APStatus }
     *     
     */
    public void setAPStatus(APStatus value) {
        this.apStatus = value;
    }

    /**
     * Gets the value of the revisionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionNumber() {
        return revisionNumber;
    }

    /**
     * Sets the value of the revisionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionNumber(String value) {
        this.revisionNumber = value;
    }

    /**
     * Gets the value of the revisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRevisionDate() {
        return revisionDate;
    }

    /**
     * Sets the value of the revisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRevisionDate(String value) {
        this.revisionDate = value;
    }

    /**
     * Gets the value of the distributeRevision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDistributeRevision() {
        return distributeRevision;
    }

    /**
     * Sets the value of the distributeRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDistributeRevision(String value) {
        this.distributeRevision = value;
    }

    /**
     * Gets the value of the poNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPONumber() {
        return poNumber;
    }

    /**
     * Sets the value of the poNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPONumber(String value) {
        this.poNumber = value;
    }

    /**
     * Gets the value of the alternatePONumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternatePONumber() {
        return alternatePONumber;
    }

    /**
     * Sets the value of the alternatePONumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternatePONumber(String value) {
        this.alternatePONumber = value;
    }

    /**
     * Gets the value of the requestor property.
     * 
     * @return
     *     possible object is
     *     {@link Requestor }
     *     
     */
    public Requestor getRequestor() {
        return requestor;
    }

    /**
     * Sets the value of the requestor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Requestor }
     *     
     */
    public void setRequestor(Requestor value) {
        this.requestor = value;
    }

    /**
     * Gets the value of the buyerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BuyerInfo }
     *     
     */
    public BuyerInfo getBuyerInfo() {
        return buyerInfo;
    }

    /**
     * Sets the value of the buyerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuyerInfo }
     *     
     */
    public void setBuyerInfo(BuyerInfo value) {
        this.buyerInfo = value;
    }

    /**
     * Gets the value of the department property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartment() {
        return department;
    }

    /**
     * Sets the value of the department property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartment(String value) {
        this.department = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the createDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateDateTime() {
        return createDateTime;
    }

    /**
     * Sets the value of the createDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateDateTime(String value) {
        this.createDateTime = value;
    }

    /**
     * Gets the value of the initialRevisionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitialRevisionDateTime() {
        return initialRevisionDateTime;
    }

    /**
     * Sets the value of the initialRevisionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitialRevisionDateTime(String value) {
        this.initialRevisionDateTime = value;
    }

    /**
     * Gets the value of the accountingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountingDate() {
        return accountingDate;
    }

    /**
     * Sets the value of the accountingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountingDate(String value) {
        this.accountingDate = value;
    }

    /**
     * Gets the value of the supplier property.
     * 
     * @return
     *     possible object is
     *     {@link Supplier }
     *     
     */
    public Supplier getSupplier() {
        return supplier;
    }

    /**
     * Sets the value of the supplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Supplier }
     *     
     */
    public void setSupplier(Supplier value) {
        this.supplier = value;
    }

    /**
     * Gets the value of the orderDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link OrderDistribution }
     *     
     */
    public OrderDistribution getOrderDistribution() {
        return orderDistribution;
    }

    /**
     * Sets the value of the orderDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderDistribution }
     *     
     */
    public void setOrderDistribution(OrderDistribution value) {
        this.orderDistribution = value;
    }

    /**
     * Gets the value of the billTo property.
     * 
     * @return
     *     possible object is
     *     {@link BillTo }
     *     
     */
    public BillTo getBillTo() {
        return billTo;
    }

    /**
     * Sets the value of the billTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillTo }
     *     
     */
    public void setBillTo(BillTo value) {
        this.billTo = value;
    }

    /**
     * Gets the value of the shipTo property.
     * 
     * @return
     *     possible object is
     *     {@link ShipTo }
     *     
     */
    public ShipTo getShipTo() {
        return shipTo;
    }

    /**
     * Sets the value of the shipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipTo }
     *     
     */
    public void setShipTo(ShipTo value) {
        this.shipTo = value;
    }

    /**
     * Gets the value of the paymentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentInfo }
     *     
     */
    public PaymentInfo getPaymentInfo() {
        return paymentInfo;
    }

    /**
     * Sets the value of the paymentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentInfo }
     *     
     */
    public void setPaymentInfo(PaymentInfo value) {
        this.paymentInfo = value;
    }

    /**
     * Gets the value of the internalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link InternalInfo }
     *     
     */
    public InternalInfo getInternalInfo() {
        return internalInfo;
    }

    /**
     * Sets the value of the internalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternalInfo }
     *     
     */
    public void setInternalInfo(InternalInfo value) {
        this.internalInfo = value;
    }

    /**
     * Gets the value of the externalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalInfo }
     *     
     */
    public ExternalInfo getExternalInfo() {
        return externalInfo;
    }

    /**
     * Sets the value of the externalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalInfo }
     *     
     */
    public void setExternalInfo(ExternalInfo value) {
        this.externalInfo = value;
    }

    /**
     * Gets the value of the freightOnBoard property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreightOnBoard() {
        return freightOnBoard;
    }

    /**
     * Sets the value of the freightOnBoard property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreightOnBoard(String value) {
        this.freightOnBoard = value;
    }

    /**
     * Gets the value of the customFieldValueSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customFieldValueSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomFieldValueSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomFieldValueSet }
     * 
     * 
     */
    public List<CustomFieldValueSet> getCustomFieldValueSet() {
        if (customFieldValueSet == null) {
            customFieldValueSet = new ArrayList<CustomFieldValueSet>();
        }
        return this.customFieldValueSet;
    }

    /**
     * Gets the value of the requisitionRef property.
     * 
     * @return
     *     possible object is
     *     {@link RequisitionRef }
     *     
     */
    public RequisitionRef getRequisitionRef() {
        return requisitionRef;
    }

    /**
     * Sets the value of the requisitionRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequisitionRef }
     *     
     */
    public void setRequisitionRef(RequisitionRef value) {
        this.requisitionRef = value;
    }

    /**
     * Gets the value of the shippingCharges property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingCharges }
     *     
     */
    public ShippingCharges getShippingCharges() {
        return shippingCharges;
    }

    /**
     * Sets the value of the shippingCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingCharges }
     *     
     */
    public void setShippingCharges(ShippingCharges value) {
        this.shippingCharges = value;
    }

    /**
     * Gets the value of the handlingCharges property.
     * 
     * @return
     *     possible object is
     *     {@link HandlingCharges }
     *     
     */
    public HandlingCharges getHandlingCharges() {
        return handlingCharges;
    }

    /**
     * Sets the value of the handlingCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlingCharges }
     *     
     */
    public void setHandlingCharges(HandlingCharges value) {
        this.handlingCharges = value;
    }

    /**
     * Gets the value of the tax1 property.
     * 
     * @return
     *     possible object is
     *     {@link Tax1 }
     *     
     */
    public Tax1 getTax1() {
        return tax1;
    }

    /**
     * Sets the value of the tax1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tax1 }
     *     
     */
    public void setTax1(Tax1 value) {
        this.tax1 = value;
    }

    /**
     * Gets the value of the tax2 property.
     * 
     * @return
     *     possible object is
     *     {@link Tax2 }
     *     
     */
    public Tax2 getTax2() {
        return tax2;
    }

    /**
     * Sets the value of the tax2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tax2 }
     *     
     */
    public void setTax2(Tax2 value) {
        this.tax2 = value;
    }

    /**
     * Gets the value of the poClauses property.
     * 
     * @return
     *     possible object is
     *     {@link POClauses }
     *     
     */
    public POClauses getPOClauses() {
        return poClauses;
    }

    /**
     * Sets the value of the poClauses property.
     * 
     * @param value
     *     allowed object is
     *     {@link POClauses }
     *     
     */
    public void setPOClauses(POClauses value) {
        this.poClauses = value;
    }

    /**
     * Gets the value of the exchangeRates property.
     * 
     * @return
     *     possible object is
     *     {@link ExchangeRates }
     *     
     */
    public ExchangeRates getExchangeRates() {
        return exchangeRates;
    }

    /**
     * Sets the value of the exchangeRates property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExchangeRates }
     *     
     */
    public void setExchangeRates(ExchangeRates value) {
        this.exchangeRates = value;
    }

}
