//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.28 at 10:22:16 AM EDT 
//


package com.sciquest.po;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "workflowStatus",
    "supplierStatus",
    "item",
    "quantity",
    "capitalExpense",
    "fixedAsset",
    "taxable",
    "lineCharges",
    "deliveryInfo",
    "supplierInfo",
    "customFieldValueSet",
    "requisitionLineRef",
    "poClauses"
})
@XmlRootElement(name = "POLine")
public class POLine {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String linenumber;
    @XmlAttribute
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String id;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlElement(name = "WorkflowStatus")
    protected WorkflowStatus workflowStatus;
    @XmlElement(name = "SupplierStatus")
    protected SupplierStatus supplierStatus;
    @XmlElement(name = "Item", required = true)
    protected Item item;
    @XmlElement(name = "Quantity", required = true)
    protected String quantity;
    @XmlElement(name = "CapitalExpense")
    protected String capitalExpense;
    @XmlElement(name = "FixedAsset")
    protected String fixedAsset;
    @XmlElement(name = "Taxable")
    protected String taxable;
    @XmlElement(name = "LineCharges", required = true)
    protected LineCharges lineCharges;
    @XmlElement(name = "DeliveryInfo")
    protected DeliveryInfo deliveryInfo;
    @XmlElement(name = "SupplierInfo")
    protected SupplierInfo supplierInfo;
    @XmlElement(name = "CustomFieldValueSet")
    protected List<CustomFieldValueSet> customFieldValueSet;
    @XmlElement(name = "RequisitionLineRef")
    protected RequisitionLineRef requisitionLineRef;
    @XmlElement(name = "POClauses")
    protected POClauses poClauses;

    /**
     * Gets the value of the linenumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinenumber() {
        return linenumber;
    }

    /**
     * Sets the value of the linenumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinenumber(String value) {
        this.linenumber = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the workflowStatus property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowStatus }
     *     
     */
    public WorkflowStatus getWorkflowStatus() {
        return workflowStatus;
    }

    /**
     * Sets the value of the workflowStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowStatus }
     *     
     */
    public void setWorkflowStatus(WorkflowStatus value) {
        this.workflowStatus = value;
    }

    /**
     * Gets the value of the supplierStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierStatus }
     *     
     */
    public SupplierStatus getSupplierStatus() {
        return supplierStatus;
    }

    /**
     * Sets the value of the supplierStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierStatus }
     *     
     */
    public void setSupplierStatus(SupplierStatus value) {
        this.supplierStatus = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Item }
     *     
     */
    public Item getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Item }
     *     
     */
    public void setItem(Item value) {
        this.item = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuantity(String value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the capitalExpense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapitalExpense() {
        return capitalExpense;
    }

    /**
     * Sets the value of the capitalExpense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapitalExpense(String value) {
        this.capitalExpense = value;
    }

    /**
     * Gets the value of the fixedAsset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixedAsset() {
        return fixedAsset;
    }

    /**
     * Sets the value of the fixedAsset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixedAsset(String value) {
        this.fixedAsset = value;
    }

    /**
     * Gets the value of the taxable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxable() {
        return taxable;
    }

    /**
     * Sets the value of the taxable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxable(String value) {
        this.taxable = value;
    }

    /**
     * Gets the value of the lineCharges property.
     * 
     * @return
     *     possible object is
     *     {@link LineCharges }
     *     
     */
    public LineCharges getLineCharges() {
        return lineCharges;
    }

    /**
     * Sets the value of the lineCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineCharges }
     *     
     */
    public void setLineCharges(LineCharges value) {
        this.lineCharges = value;
    }

    /**
     * Gets the value of the deliveryInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryInfo }
     *     
     */
    public DeliveryInfo getDeliveryInfo() {
        return deliveryInfo;
    }

    /**
     * Sets the value of the deliveryInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryInfo }
     *     
     */
    public void setDeliveryInfo(DeliveryInfo value) {
        this.deliveryInfo = value;
    }

    /**
     * Gets the value of the supplierInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SupplierInfo }
     *     
     */
    public SupplierInfo getSupplierInfo() {
        return supplierInfo;
    }

    /**
     * Sets the value of the supplierInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SupplierInfo }
     *     
     */
    public void setSupplierInfo(SupplierInfo value) {
        this.supplierInfo = value;
    }

    /**
     * Gets the value of the customFieldValueSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customFieldValueSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomFieldValueSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CustomFieldValueSet }
     * 
     * 
     */
    public List<CustomFieldValueSet> getCustomFieldValueSet() {
        if (customFieldValueSet == null) {
            customFieldValueSet = new ArrayList<CustomFieldValueSet>();
        }
        return this.customFieldValueSet;
    }

    /**
     * Gets the value of the requisitionLineRef property.
     * 
     * @return
     *     possible object is
     *     {@link RequisitionLineRef }
     *     
     */
    public RequisitionLineRef getRequisitionLineRef() {
        return requisitionLineRef;
    }

    /**
     * Sets the value of the requisitionLineRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequisitionLineRef }
     *     
     */
    public void setRequisitionLineRef(RequisitionLineRef value) {
        this.requisitionLineRef = value;
    }

    /**
     * Gets the value of the poClauses property.
     * 
     * @return
     *     possible object is
     *     {@link POClauses }
     *     
     */
    public POClauses getPOClauses() {
        return poClauses;
    }

    /**
     * Sets the value of the poClauses property.
     * 
     * @param value
     *     allowed object is
     *     {@link POClauses }
     *     
     */
    public void setPOClauses(POClauses value) {
        this.poClauses = value;
    }

}
