//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.28 at 10:22:16 AM EDT 
//


package com.sciquest.po;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hasBackorderedItems",
    "hasCancelledItems",
    "hasSupplierEdits",
    "hasShippedItems"
})
@XmlRootElement(name = "SupplierStatus")
public class SupplierStatus {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String status;
    @XmlElement(name = "HasBackorderedItems", required = true)
    protected String hasBackorderedItems;
    @XmlElement(name = "HasCancelledItems")
    protected String hasCancelledItems;
    @XmlElement(name = "HasSupplierEdits", required = true)
    protected String hasSupplierEdits;
    @XmlElement(name = "HasShippedItems", required = true)
    protected String hasShippedItems;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the hasBackorderedItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasBackorderedItems() {
        return hasBackorderedItems;
    }

    /**
     * Sets the value of the hasBackorderedItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasBackorderedItems(String value) {
        this.hasBackorderedItems = value;
    }

    /**
     * Gets the value of the hasCancelledItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasCancelledItems() {
        return hasCancelledItems;
    }

    /**
     * Sets the value of the hasCancelledItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasCancelledItems(String value) {
        this.hasCancelledItems = value;
    }

    /**
     * Gets the value of the hasSupplierEdits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasSupplierEdits() {
        return hasSupplierEdits;
    }

    /**
     * Sets the value of the hasSupplierEdits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasSupplierEdits(String value) {
        this.hasSupplierEdits = value;
    }

    /**
     * Gets the value of the hasShippedItems property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHasShippedItems() {
        return hasShippedItems;
    }

    /**
     * Sets the value of the hasShippedItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHasShippedItems(String value) {
        this.hasShippedItems = value;
    }

}
