//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.28 at 10:22:16 AM EDT 
//


package com.sciquest.po;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "percentageRate",
    "flatChargeByLine",
    "flatChargeByOrder",
    "freeThresholdLimit"
})
@XmlRootElement(name = "TSHConfig")
public class TSHConfig {

    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String override;
    @XmlElement(name = "PercentageRate")
    protected String percentageRate;
    @XmlElement(name = "FlatChargeByLine")
    protected FlatChargeByLine flatChargeByLine;
    @XmlElement(name = "FlatChargeByOrder")
    protected FlatChargeByOrder flatChargeByOrder;
    @XmlElement(name = "FreeThresholdLimit")
    protected FreeThresholdLimit freeThresholdLimit;

    /**
     * Gets the value of the override property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOverride() {
        return override;
    }

    /**
     * Sets the value of the override property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOverride(String value) {
        this.override = value;
    }

    /**
     * Gets the value of the percentageRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPercentageRate() {
        return percentageRate;
    }

    /**
     * Sets the value of the percentageRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPercentageRate(String value) {
        this.percentageRate = value;
    }

    /**
     * Gets the value of the flatChargeByLine property.
     * 
     * @return
     *     possible object is
     *     {@link FlatChargeByLine }
     *     
     */
    public FlatChargeByLine getFlatChargeByLine() {
        return flatChargeByLine;
    }

    /**
     * Sets the value of the flatChargeByLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlatChargeByLine }
     *     
     */
    public void setFlatChargeByLine(FlatChargeByLine value) {
        this.flatChargeByLine = value;
    }

    /**
     * Gets the value of the flatChargeByOrder property.
     * 
     * @return
     *     possible object is
     *     {@link FlatChargeByOrder }
     *     
     */
    public FlatChargeByOrder getFlatChargeByOrder() {
        return flatChargeByOrder;
    }

    /**
     * Sets the value of the flatChargeByOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlatChargeByOrder }
     *     
     */
    public void setFlatChargeByOrder(FlatChargeByOrder value) {
        this.flatChargeByOrder = value;
    }

    /**
     * Gets the value of the freeThresholdLimit property.
     * 
     * @return
     *     possible object is
     *     {@link FreeThresholdLimit }
     *     
     */
    public FreeThresholdLimit getFreeThresholdLimit() {
        return freeThresholdLimit;
    }

    /**
     * Sets the value of the freeThresholdLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreeThresholdLimit }
     *     
     */
    public void setFreeThresholdLimit(FreeThresholdLimit value) {
        this.freeThresholdLimit = value;
    }

}
